# Generated by Django 5.1.7 on 2025-03-28 05:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_specialty_alter_doctors_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thuốc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá tiền')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng trong kho')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày kê đơn')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tổng tiền')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctors', verbose_name='Bác sĩ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients', verbose_name='Bệnh nhân')),
            ],
            options={
                'ordering': ['-date_prescribed'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Hướng dẫn sử dụng')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá tiền')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicine', verbose_name='Thuốc')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
        ),
    ]
