# Generated by Django 5.1.7 on 2025-04-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remainder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
